#!/bin/bash

RED="\e[31m"
NOCOLOR="\e[0m"
CYAN="\e[36m"

wholedir="$(pwd)"
dirname="$(basename $wholedir)"

if [ -d build ]
then
    echo -e "Are you sure? (y/n): "
    read yon
    if [ $yon == "y" ]
    then 
        echo -e "[$dirname] ${CYAN}Cleaning Up${NOCOLOR}"
        rm -r build
        echo -e "[$dirname] ${CYAN}Cleaning Up: DONE${NOCOLOR}"
    fi
    else
        echo -e "[$dirname] ${RED}ERROR${NOCOLOR}: No build directory found"
fi
