#!/bin/bash



RED="\e[31m"
NOCOLOR="\e[0m"
CYAN="\e[36m"

wholedir="$(pwd)"
dirname="$(basename $wholedir)"

if [ -f build/Makefile ]
then
    echo -e "${RED}pconfigure: build directory already exist, reconfigure? (y/n) :${NOCOLOR} "
    read yon
    if [ $yon == "y" ]
    then
        echo -e "[$dirname] ${CYAN}Config: Starting${NOCOLOR}"
        rm -r build
        mkdir build
        cd build
        cmake ..
        cd ..
        echo -e "[$dirname] ${CYAN}Config: Done${NOCOLOR}"
    fi
else
    echo -e "[$dirname] ${CYAN}Config: Starting${NOCOLOR}"
    mkdir build
    cd build
    cmake ..
    cd ..
    echo -e "[$dirname] ${CYAN}Config: Done${NOCOLOR}"
fi
