#!/bin/bash

RED="\e[31m"
NOCOLOR="\e[0m"
CYAN="\e[36m"

wholedir="$(pwd)"
dirname="$(basename $wholedir)"


if [ -f go ]
then
    if [ -f $dirname ]
    then
        rm $dirname
    fi
    echo -e "[$dirname] ${CYAN}Build: Starting${NOCOLOR}"
    go build -o $dirname main.go
    
    if (( $? > 0 ))
    then
        echo -e "[$dirname] ${RED}Build: Failed${NOCOLOR}"
        exit 1
    fi

    echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
elif [ -f asm ]
then
    if [ -f $dirname ]
    then
        rm $dirname
    fi
    echo -e "[$dirname] ${CYAN}Build: Starting${NOCOLOR}"
    gcc $dirname.s -c -g

    if (( $? > 0 ))
    then
        echo -e "[$dirname] ${RED}Build: Failed on assembling${NOCOLOR}"
        exit 1
    fi

    ld -o $dirname $dirname.o -nostdlib -static

    if (( $? > 0 ))
    then
        rm $dirname.o
        echo -e "[$dirname] ${RED}Build: Failed on linking${NOCOLOR}"
        exit 1
    fi
    rm $dirname.o 
    echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"

else
if [ -f "build/Makefile" ]; then
    echo -e "[$dirname] ${CYAN}Build: Starting${NOCOLOR}"
    cd build
    make -j `nproc`
    if (( $? > 0 ))
    then
        echo -e "[$dirname] ${RED}Build: Failed${NOCOLOR}"
        exit 1
    fi
    cd ..
    echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
else 
    echo -e "[$dirname] ${RED}No config files found, generate config? (y/n):${NOCOLOR} "
    read yon
    if [ $yon == "y" ]
    then
        pconfigure
        echo -e "[$dirname] ${CYAN}Build: Starting${NOCOLOR}"
        cd build
        make -j `nproc`
        if (( $? > 0 ))
        then
            echo -e "[$dirname] ${RED}Build: Failed${NOCOLOR}"
            exit 1
        fi
        cd ..
        echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
    fi
fi
fi
