#!/bin/bash

RED="\e[31m"
NOCOLOR="\e[0m"
CYAN="\e[36m"

wholedir="$(pwd)"
dirname="$(basename $wholedir)"


if [ -f go ]
then
go build -o $dirname main.go
else
if [ -f "build/Makefile" ]; then
    echo -e "[] ${CYAN}Build: Starting${NOCOLOR}"
    cd build
    make -j `nproc`
    cd ..
    echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
else 
    echo -e "[$dirname] ${RED}No config files found, generate config? (y/n):${NOCOLOR} "
    read yon
    if [ $yon == "y" ]
    then
        pconfigure
        echo -e "[$dirname] ${CYAN}Build: Starting${NOCOLOR}"
        cd build
        make -j `nproc`
        cd ..
        echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
    fi
fi
fi