#!/bin/bash

RED="\e[31m"
NOCOLOR="\e[0m"
CYAN="\e[36m"

if [ -z $1 ]
then
    echo "Name of GO package: "
    read name
else
    name=$1
fi

if [ -d $name ]
then
    echo -e "${RED}Package already exists! ($name)"
else
    echo -e "[$name] ${CYAN} Creating package: Starting${NOCOLOR}"
    echo -e "[$name] ${CYAN} Creating directory${NOCOLOR}"
    mkdir $name
    echo -e "[$name] ${CYAN} Entering directory${NOCOLOR}"
    cd $name
    echo -e "[$name] ${CYAN} Initializing git${NOCOLOR}"
    git init

    echo 'package main
import "fmt"
func main() {                                                                                                                                                            
    fmt.Printf("Hello, go!\n")                                                                                                                                                
}' > main.go    
    

    touch go
    echo -e "[$name] ${CYAN} Creating package: Done${NOCOLOR}"
fi
