#!/bin/bash

RED="\e[31m"
NOCOLOR="\e[0m"
CYAN="\e[36m"

pmake
wholedir="$(pwd)"
dirname="$(basename $wholedir)"
echo -e "[$dirname] ${CYAN}Run: Starting${NOCOLOR}"
if [ -f go ]
then
    ./$dirname
else
    ./build/$dirname
fi
echo -e "[$dirname] ${CYAN}Run: Done${NOCOLOR}"
